spring.application.name=BookStoreSystem
csv.file.path=src/main/resources/books_catalog.csv
report.file.path=book-report.txt

server.port=8000

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always